### ISSUE TITLE
cannot use user's own erlang packages local repo

### ISSUE THREAD

**Issue by wenchma** [chef-cookbooks/erlang#20]
In actual deployment environment, erlang packages exist in local repo, and cannot use erlang repo link to http://packages.erlang_solutions.com.
But this cookbook doesn't support configuring distro version, so a new attribute is needed.

related code segment:
https://github.com/opscode-cookbooks/erlang/blob/master/recipes/package.rb#L43

**Comment by cmluciano** [comment]
I've commented on your PR

**Comment by cheeseplus** [comment]
This seems to have been resolved by #29
