### ISSUE TITLE
When building from source, not_if fails for any minor releases

### ISSUE THREAD

**Issue by spatula75** [chef-cookbooks/erlang#39]
There is a not_if in the bash block that evaluates `'erlang:display(erlang:system_info(otp_release)), halt().'`; however, this command returns only the major release number of otp.  So if the version is, say, 18.3, then the `grep` in that `not_if` will be looking for 18.3, but the eval will return the string `"18"`.

The incredibly ugly command:

`erl -eval '{ok, Version} = file:read_file(filename:join([code:root_dir(), "releases", erlang:system_info(otp_release), "OTP_VERSION"])), erlang:display(erlang:binary_to_list(Version)), halt().' -noshell`

will retrieve the full erlang version for versions >= 17.  See also http://stackoverflow.com/a/34326368/3757951

**Comment by cheeseplus** [comment]
The need for this will go away shortly because we're letting ohai do this now https://github.com/chef/ohai/pull/916

**Comment by cheeseplus** [comment]
So looks like we added this check but as I was investigating the above PR it seems we swing the other way and break pre-17 Erlang which doesn't have a release file - I've got PRs incoming to fix ohai and the cookbook to account for both but this issue can be closed.
