### ISSUE TITLE
Cannot update erlang to newer version

### ISSUE THREAD

**Issue by aduckardt** [chef-cookbooks/erlang#44]
### Cookbook version
4.0.0

### Chef-client version
Chef: 12.4.3

### Platform Details
CentOS 7:  3.10.0-327.13.1.el7.x86_64

### Scenario:
Trying to install 19.1-1 version of erlang

### Steps to Reproduce:
I'm trying to install RabbitMQ via  https://github.com/rabbitmq/chef-cookbook  they use this erlang cookbook as dependency. 
Firstly, I used default version of erlang but some rabbitmq plugins does not work with it. So I updated erlang version in attributes as shown bellow:
  
default['erlang']['install_method'] = 'esl'
default['erlang']['esl']['version'] = '19.1-1'
default['rabbitmq']['esl-erlang_package'] = 'esl-erlang-compat-R1801-1.noarch.rpm?raw=true'
default['rabbitmq']['esl-erlang_package_url'] = 'https://github.com/jasonmcintosh/esl-erlang-compat/blob/master/rpmbuild/RPMS/noarch/'

But chef fails to update already installed erlang. I had to remove previous installation manually and then rerun chef client. 

### Expected Result:
erlang should be updated  if there is older version is installed

### Actual Result:

Transaction check error:
 file /usr/bin/epmd from install of esl-erlang-19.1-1.x86_64 conflicts with file from package erlang-erts-R16B-03.17.el7.x86_64
 file /usr/bin/erl from install of esl-erlang-19.1-1.x86_64 conflicts with file from package erlang-erts-R16B-03.17.el7.x86_64
 file /usr/bin/erlc from install of esl-erlang-19.1-1.x86_64 conflicts with file from package erlang-erts-R16B-03.17.el7.x86_64
 file /usr/bin/escript from install of esl-erlang-19.1-1.x86_64 conflicts with file from package erlang-erts-R16B-03.17.el7.x86_64
 file /usr/bin/run_erl from install of esl-erlang-19.1-1.x86_64 conflicts with file from package erlang-erts-R16B-03.17.el7.x86_64
 file /usr/bin/to_erl from install of esl-erlang-19.1-1.x86_64 conflicts with file from package erlang-erts-R16B-03.17.el7.x86_64
 file /usr/bin/dialyzer from install of esl-erlang-19.1-1.x86_64 conflicts with file from package erlang-dialyzer-R16B-03.17.el7.x86_64
 file /usr/bin/typer from install of esl-erlang-19.1-1.x86_64 conflicts with file from package erlang-typer-R16B-03.17.el7.x86_64
 file /usr/bin/ct_run from install of esl-erlang-19.1-1.x86_64 conflicts with file from package erlang-common_test-R16B-03.17.el7.x86_64

**Comment by tas50** [comment]
@aduckardt  Can you include the full output of the Chef run when it failed to upgrade?

**Comment by aduckardt** [comment]
@tas50 You can find chef log in attachments
[erlang_cookbook error.txt](https://github.com/chef-cookbooks/erlang/files/625872/erlang_cookbook.error.txt)

**Comment by cheeseplus** [comment]
This seems to me that you're trying to go from ESL erlang to non-esl erlang which is yum is freaking out.

**Comment by cheeseplus** [comment]
I'm closing this one as the logs indicate trying to switch from erlang to esl-erlang which isn't something the cookbook can easily support. If you want to use ESL builds, only use the ESL recipe and make sure distro Erlang packages aren't present.

**Comment by solarisy** [comment]
yum remove erlang-erts-R16B-03.17.el7.x86_64
