### ISSUE TITLE
Allow newer yum cookbook

### ISSUE THREAD

**Issue by julian7** [chef-cookbooks/erlang#54]
### Cookbook version
4.1.0

### Chef-client version
varies: v >= 12.5.1

### Platform Details
varies: OEL6, centos7

### Scenario:
I'd like to use newer yum cookbooks.

Even the latest erlang cookbook has the following dependency:

```
"yum":"~> 3.0"
```

Since then, yum cookbook has been updated to 5.0.0, to follow suit with recent chef client changes.

**Comment by iennae** [comment]
@julian7 You can use newer yum cookbooks. The metadata just sets the minimum version that is supported. When I do a test converge today I see:

       [2017-03-02T04:06:21+00:00] INFO: Loading cookbooks [erlang@4.1.0, apt@6.0.1, yum@5.0.0, yum-epel@2.1.1, yum-erlang_solutions@1.0.3, build-essential@8.0.0, compat_resource@12.16.3, seven_zip@2.0.2, mingw@2.0.0, windows@2.1.1, ohai@5.0.0]

You'll note that it's pulling in the latest version of the yum cookbook. Do you perhaps have some kind of version lock in your environment that is preventing the use of the later version of the yum cookbook?

**Comment by iennae** [comment]
It's been pointed out that this changed on github but hasn't been released onto supermarket yet. Apologies for the confusion! Looks like https://github.com/chef-cookbooks/erlang/commit/aca449b42fc7ff06a5218fa7f461cc5806787b0a resolved the problem. I'm going to go ahead and make a release to fix this.

**Comment by iennae** [comment]
This should be fixed with version 4.1.1 of this cookbook.
