### ISSUE TITLE
Erlang version not found in yum via knife

### ISSUE THREAD

**Issue by sljuka** [chef-cookbooks/erlang#58]
Hi,

I'm having small trouble installing a specific version of erlang via knife. Dunno if this is an issue or a fail on my side.

### Cookbook version
cookbook 'erlang', '~> 5.1.0'

### Chef-client version
Chef Development Kit Version: 1.3.43
chef-client version: 12.19.36
delivery version: master (dd319aa632c2f550c92a2172b9d1226478fea997)
berks version: 5.6.4
kitchen version: 1.16.0

### Platform Details
Centos 7 (64 bits), OVH cloud provider

### Scenario:
I am trying to install a specific version of esl-erlang package using yum (19.3-1)

### Steps to Reproduce:
I am trying to deploy an elixir (phoenix) app, and need a older version of erlang, mentioned above. 
- Create a role in chef-server. role json's attributes looks like this:
```
   "default_attributes": {
     "erlang": {
       "package": {
         "version": "19.3-1"
       },
       "source": {
         "version": "19.3-1"
       },
       "esl": {
         "version": "19.3-1"
       }
     }
   },
```
- ran knife-ssh on this role to update all nodes with this role

### Expected Result:
Instalation of the specified erlang version on node (using yum)

### Actual Result:
After running knife ssh on the role of this node, there was an error in the console:
```
================================================================================
79.137.73.128     Error executing action `install` on resource 'yum_package[erlang]'
79.137.73.128     ================================================================================
79.137.73.128
79.137.73.128     Chef::Exceptions::Package
79.137.73.128     -------------------------
79.137.73.128     Version ["19.3-1"] of ["erlang"] not found. Did you specify both version and release? (version-release, e.g. 1.84-10.fc6)
```
After ssh-ing into the node and running
`yum install esl-erlang-19.3`
There was a package available
```
Installing:
 esl-erlang                                x86_64                                19.3-1
```
so the package is available when doing it manualy, but not when doing it via knife.

I might be specifying the version in my `role.json` badly, tried '19.3' and 19.3-1 but it didn't work...

**Comment by sljuka** [comment]
This is probably not related to this cookbook. It seems this is also the case in other cookbooks:
https://github.com/chef-cookbooks/docker/issues/93
But I still don't get what I need to enter as value for package for it to find the correct erlang version

**Comment by iennae** [comment]
Are you using the esl recipe? https://github.com/chef-cookbooks/erlang/blob/master/recipes/esl.rb

When I look at what is available using default repos, it's R16B. Can you provide the run_list of what you are doing. Thanks.

**Comment by iennae** [comment]
If you use default and esl at the same time it will cause a conflict, but if I specify the run_list erlang::esl and specify the attribute 


it successfully converges:


       Recipe: erlang::esl
         * yum_package[esl-erlang] action install
           - install version 19.3-1 of package esl-erlang

       Running handlers:
       Running handlers complete
       Chef Client finished, 11/17 resources updated in 09 minutes 44 seconds
       Finished converging <default-centos-73> (10m1.74s).

**Comment by sljuka** [comment]
This is my role definition including the run list:
```
{
   "name": "builder",
   "description": "Phoenix build server role.",
   "json_class": "Chef::Role",
   "default_attributes": {
     "erlang": {
       "package": {
         "version": "19.3-1"
       },
       "source": {
         "version": "19.3-1"
       },
       "esl": {
         "version": "19.3"
       }
     }
   },
   "override_attributes": {},
   "chef_type": "role",
   "run_list": [
     "recipe[builder_init::default]",
     "recipe[git::default]",
     "recipe[nodejs::default]",
     "recipe[nodejs::npm]",
     "recipe[erlang::default]",
     "recipe[elixir::default]"
   ],
   "env_run_lists": {}
}
```
I'm new to chef and not sure if this follows correct chef conventions.
Anyway I used only default recipe, will try ::esl now.
Answer is much appreciated :)

**Comment by sljuka** [comment]
Replaced default recipe with esl, removed package and source attributes and it worked. 👍

**Comment by iennae** [comment]
@sljuka Thanks for the confirmation. I appreciate you letting us know that worked!
