### ISSUE TITLE
Upload erlang 6.1.1 to Chef Supermarket

### ISSUE THREAD

**Issue by yardinicwaller** [chef-cookbooks/erlang#62]
Supermarket is still showing v6.1.0 as the latest available version of this cookbook, but that version has buggy metadata that breaks installation with knife (`knife cookbook site install erlang`).

The metadata issue was [fixed](https://github.com/chef-cookbooks/erlang/commit/0548308d9281a15d92231fa7043130e25a483c43#diff-9fd042d4cd1e8f82894bbd7dffb313ec) a month ago and there is a commit for the [6.1.1 release](https://github.com/chef-cookbooks/erlang/commit/ada60718f6ecb442fd416659c9c0a1a3ccb3d7ba) but the release was never tagged or uploaded to Chef Supermarket.

Please upload 6.1.1 to Supermarket. (And consider revoking 6.1.0 because of the broken installation.)

**Comment by tas50** [comment]
Pushed to the supermarket. I think the push command failed before.
